/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Escrow {
      
    export type EscrowInfoStruct = {id: BigNumberish, buyer: AddressLike, seller: AddressLike, arbitrator: AddressLike, amount: BigNumberish, deadline: BigNumberish, createdAt: BigNumberish, platformFee: BigNumberish, status: BigNumberish, exists: boolean}

    export type EscrowInfoStructOutput = [id: bigint, buyer: string, seller: string, arbitrator: string, amount: bigint, deadline: bigint, createdAt: bigint, platformFee: bigint, status: bigint, exists: boolean] & {id: bigint, buyer: string, seller: string, arbitrator: string, amount: bigint, deadline: bigint, createdAt: bigint, platformFee: bigint, status: bigint, exists: boolean }
  
    }

  export interface EscrowInterface extends Interface {
    getFunction(nameOrSignature: "FEE_DENOMINATOR" | "FEE_TIMELOCK" | "MAX_FEE" | "acceptEscrow" | "accumulatedFees" | "approvePayment" | "cancelEscrow" | "createEscrow" | "depositETH" | "executePlatformFee" | "feeChangeUnlockTime" | "fundEscrow" | "getBuyerEscrows" | "getEscrow" | "getSellerEscrows" | "markDelivered" | "nextEscrowId" | "owner" | "pause" | "paused" | "pendingFee" | "pendingWithdrawals" | "platformFee" | "proposePlatformFee" | "raiseDispute" | "rejectEscrow" | "renounceOwnership" | "rescueETH" | "resolveDispute" | "totalLockedFunds" | "totalPendingWithdrawals" | "transferOwnership" | "unpause" | "withdraw" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeRaised" | "DisputeResolved" | "ETHDeposited" | "ETHRescued" | "EscrowAccepted" | "EscrowCancelled" | "EscrowCreated" | "EscrowFunded" | "FeesWithdrawn" | "OwnershipTransferred" | "Paused" | "PaymentReleased" | "PlatformFeeProposed" | "PlatformFeeUpdated" | "Unpaused" | "Withdrawn" | "WorkDelivered"): EventFragment;

    encodeFunctionData(functionFragment: 'FEE_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE_TIMELOCK', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'accumulatedFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'approvePayment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createEscrow', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'executePlatformFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeChangeUnlockTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBuyerEscrows', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSellerEscrows', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'markDelivered', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextEscrowId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingWithdrawals', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'platformFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposePlatformFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'raiseDispute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rescueETH', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'totalLockedFunds', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalPendingWithdrawals', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawFees', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'FEE_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE_TIMELOCK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approvePayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executePlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeChangeUnlockTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBuyerEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSellerEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markDelivered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextEscrowId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingWithdrawals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposePlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rescueETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalLockedFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPendingWithdrawals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace DisputeRaisedEvent {
      export type InputTuple = [escrowId: BigNumberish, raisedBy: AddressLike];
      export type OutputTuple = [escrowId: bigint, raisedBy: string];
      export interface OutputObject {escrowId: bigint, raisedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [escrowId: BigNumberish, winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, winner: string, amount: bigint];
      export interface OutputObject {escrowId: bigint, winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ETHDepositedEvent {
      export type InputTuple = [sender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, amount: bigint];
      export interface OutputObject {sender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ETHRescuedEvent {
      export type InputTuple = [receiver: AddressLike, amount: BigNumberish];
      export type OutputTuple = [receiver: string, amount: bigint];
      export interface OutputObject {receiver: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowAcceptedEvent {
      export type InputTuple = [escrowId: BigNumberish, seller: AddressLike];
      export type OutputTuple = [escrowId: bigint, seller: string];
      export interface OutputObject {escrowId: bigint, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCancelledEvent {
      export type InputTuple = [escrowId: BigNumberish, cancelledBy: AddressLike];
      export type OutputTuple = [escrowId: bigint, cancelledBy: string];
      export interface OutputObject {escrowId: bigint, cancelledBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCreatedEvent {
      export type InputTuple = [escrowId: BigNumberish, buyer: AddressLike, seller: AddressLike, arbitrator: AddressLike, amount: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [escrowId: bigint, buyer: string, seller: string, arbitrator: string, amount: bigint, deadline: bigint];
      export interface OutputObject {escrowId: bigint, buyer: string, seller: string, arbitrator: string, amount: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowFundedEvent {
      export type InputTuple = [escrowId: BigNumberish, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, buyer: string, amount: bigint];
      export interface OutputObject {escrowId: bigint, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesWithdrawnEvent {
      export type InputTuple = [receiver: AddressLike, amount: BigNumberish];
      export type OutputTuple = [receiver: string, amount: bigint];
      export interface OutputObject {receiver: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentReleasedEvent {
      export type InputTuple = [escrowId: BigNumberish, seller: AddressLike, sellerAmount: BigNumberish, platformFee: BigNumberish];
      export type OutputTuple = [escrowId: bigint, seller: string, sellerAmount: bigint, platformFee: bigint];
      export interface OutputObject {escrowId: bigint, seller: string, sellerAmount: bigint, platformFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlatformFeeProposedEvent {
      export type InputTuple = [newFee: BigNumberish, unlockTime: BigNumberish];
      export type OutputTuple = [newFee: bigint, unlockTime: bigint];
      export interface OutputObject {newFee: bigint, unlockTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlatformFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [account: AddressLike, amount: BigNumberish];
      export type OutputTuple = [account: string, amount: bigint];
      export interface OutputObject {account: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkDeliveredEvent {
      export type InputTuple = [escrowId: BigNumberish, seller: AddressLike];
      export type OutputTuple = [escrowId: bigint, seller: string];
      export interface OutputObject {escrowId: bigint, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Escrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): Escrow;
    waitForDeployment(): Promise<this>;

    interface: EscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    FEE_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE_TIMELOCK: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptEscrow: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    accumulatedFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    approvePayment: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelEscrow: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createEscrow: TypedContractMethod<
      [seller: AddressLike, arbitrator: AddressLike, amount: BigNumberish, deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositETH: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    executePlatformFee: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    feeChangeUnlockTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fundEscrow: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getBuyerEscrows: TypedContractMethod<
      [buyer: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getEscrow: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [Escrow.EscrowInfoStructOutput],
      'view'
    >
    

    
    getSellerEscrows: TypedContractMethod<
      [seller: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    markDelivered: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    nextEscrowId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pendingFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pendingWithdrawals: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    platformFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposePlatformFee: TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    raiseDispute: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rejectEscrow: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rescueETH: TypedContractMethod<
      [receiver: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [escrowId: BigNumberish, winner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalLockedFunds: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalPendingWithdrawals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawFees: TypedContractMethod<
      [receiver: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'FEE_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE_TIMELOCK'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptEscrow'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'accumulatedFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approvePayment'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelEscrow'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [seller: AddressLike, arbitrator: AddressLike, amount: BigNumberish, deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositETH'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'executePlatformFee'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeChangeUnlockTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fundEscrow'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getBuyerEscrows'): TypedContractMethod<
      [buyer: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getEscrow'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [Escrow.EscrowInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSellerEscrows'): TypedContractMethod<
      [seller: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'markDelivered'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextEscrowId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pendingFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingWithdrawals'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'platformFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposePlatformFee'): TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectEscrow'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rescueETH'): TypedContractMethod<
      [receiver: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [escrowId: BigNumberish, winner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalLockedFunds'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalPendingWithdrawals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [receiver: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DisputeRaised'): TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'ETHDeposited'): TypedContractEvent<ETHDepositedEvent.InputTuple, ETHDepositedEvent.OutputTuple, ETHDepositedEvent.OutputObject>;
getEvent(key: 'ETHRescued'): TypedContractEvent<ETHRescuedEvent.InputTuple, ETHRescuedEvent.OutputTuple, ETHRescuedEvent.OutputObject>;
getEvent(key: 'EscrowAccepted'): TypedContractEvent<EscrowAcceptedEvent.InputTuple, EscrowAcceptedEvent.OutputTuple, EscrowAcceptedEvent.OutputObject>;
getEvent(key: 'EscrowCancelled'): TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'EscrowFunded'): TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PaymentReleased'): TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
getEvent(key: 'PlatformFeeProposed'): TypedContractEvent<PlatformFeeProposedEvent.InputTuple, PlatformFeeProposedEvent.OutputTuple, PlatformFeeProposedEvent.OutputObject>;
getEvent(key: 'PlatformFeeUpdated'): TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
getEvent(key: 'WorkDelivered'): TypedContractEvent<WorkDeliveredEvent.InputTuple, WorkDeliveredEvent.OutputTuple, WorkDeliveredEvent.OutputObject>;

    filters: {
      
      'DisputeRaised(uint256,address)': TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
      DisputeRaised: TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
    

      'DisputeResolved(uint256,address,uint256)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'ETHDeposited(address,uint256)': TypedContractEvent<ETHDepositedEvent.InputTuple, ETHDepositedEvent.OutputTuple, ETHDepositedEvent.OutputObject>;
      ETHDeposited: TypedContractEvent<ETHDepositedEvent.InputTuple, ETHDepositedEvent.OutputTuple, ETHDepositedEvent.OutputObject>;
    

      'ETHRescued(address,uint256)': TypedContractEvent<ETHRescuedEvent.InputTuple, ETHRescuedEvent.OutputTuple, ETHRescuedEvent.OutputObject>;
      ETHRescued: TypedContractEvent<ETHRescuedEvent.InputTuple, ETHRescuedEvent.OutputTuple, ETHRescuedEvent.OutputObject>;
    

      'EscrowAccepted(uint256,address)': TypedContractEvent<EscrowAcceptedEvent.InputTuple, EscrowAcceptedEvent.OutputTuple, EscrowAcceptedEvent.OutputObject>;
      EscrowAccepted: TypedContractEvent<EscrowAcceptedEvent.InputTuple, EscrowAcceptedEvent.OutputTuple, EscrowAcceptedEvent.OutputObject>;
    

      'EscrowCancelled(uint256,address)': TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
      EscrowCancelled: TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
    

      'EscrowCreated(uint256,address,address,address,uint256,uint256)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'EscrowFunded(uint256,address,uint256)': TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
      EscrowFunded: TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
    

      'FeesWithdrawn(address,uint256)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PaymentReleased(uint256,address,uint256,uint256)': TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
      PaymentReleased: TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
    

      'PlatformFeeProposed(uint96,uint256)': TypedContractEvent<PlatformFeeProposedEvent.InputTuple, PlatformFeeProposedEvent.OutputTuple, PlatformFeeProposedEvent.OutputObject>;
      PlatformFeeProposed: TypedContractEvent<PlatformFeeProposedEvent.InputTuple, PlatformFeeProposedEvent.OutputTuple, PlatformFeeProposedEvent.OutputObject>;
    

      'PlatformFeeUpdated(uint96,uint96)': TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
      PlatformFeeUpdated: TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    

      'WorkDelivered(uint256,address)': TypedContractEvent<WorkDeliveredEvent.InputTuple, WorkDeliveredEvent.OutputTuple, WorkDeliveredEvent.OutputObject>;
      WorkDelivered: TypedContractEvent<WorkDeliveredEvent.InputTuple, WorkDeliveredEvent.OutputTuple, WorkDeliveredEvent.OutputObject>;
    
    };
  }