/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, FunctionFragment, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../common.js"
  

  export interface EscrowEventsInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "DisputeRaised" | "DisputeResolved" | "ETHDeposited" | "ETHRescued" | "EscrowAccepted" | "EscrowCancelled" | "EscrowCreated" | "EscrowFunded" | "FeesWithdrawn" | "PaymentReleased" | "PlatformFeeProposed" | "PlatformFeeUpdated" | "Withdrawn" | "WorkDelivered"): EventFragment;

    

    
  }

  
    export namespace DisputeRaisedEvent {
      export type InputTuple = [escrowId: BigNumberish, raisedBy: AddressLike];
      export type OutputTuple = [escrowId: bigint, raisedBy: string];
      export interface OutputObject {escrowId: bigint, raisedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [escrowId: BigNumberish, winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, winner: string, amount: bigint];
      export interface OutputObject {escrowId: bigint, winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ETHDepositedEvent {
      export type InputTuple = [sender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, amount: bigint];
      export interface OutputObject {sender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ETHRescuedEvent {
      export type InputTuple = [receiver: AddressLike, amount: BigNumberish];
      export type OutputTuple = [receiver: string, amount: bigint];
      export interface OutputObject {receiver: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowAcceptedEvent {
      export type InputTuple = [escrowId: BigNumberish, seller: AddressLike];
      export type OutputTuple = [escrowId: bigint, seller: string];
      export interface OutputObject {escrowId: bigint, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCancelledEvent {
      export type InputTuple = [escrowId: BigNumberish, cancelledBy: AddressLike];
      export type OutputTuple = [escrowId: bigint, cancelledBy: string];
      export interface OutputObject {escrowId: bigint, cancelledBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCreatedEvent {
      export type InputTuple = [escrowId: BigNumberish, buyer: AddressLike, seller: AddressLike, arbitrator: AddressLike, amount: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [escrowId: bigint, buyer: string, seller: string, arbitrator: string, amount: bigint, deadline: bigint];
      export interface OutputObject {escrowId: bigint, buyer: string, seller: string, arbitrator: string, amount: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowFundedEvent {
      export type InputTuple = [escrowId: BigNumberish, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, buyer: string, amount: bigint];
      export interface OutputObject {escrowId: bigint, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesWithdrawnEvent {
      export type InputTuple = [receiver: AddressLike, amount: BigNumberish];
      export type OutputTuple = [receiver: string, amount: bigint];
      export interface OutputObject {receiver: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentReleasedEvent {
      export type InputTuple = [escrowId: BigNumberish, seller: AddressLike, sellerAmount: BigNumberish, platformFee: BigNumberish];
      export type OutputTuple = [escrowId: bigint, seller: string, sellerAmount: bigint, platformFee: bigint];
      export interface OutputObject {escrowId: bigint, seller: string, sellerAmount: bigint, platformFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlatformFeeProposedEvent {
      export type InputTuple = [newFee: BigNumberish, unlockTime: BigNumberish];
      export type OutputTuple = [newFee: bigint, unlockTime: bigint];
      export interface OutputObject {newFee: bigint, unlockTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlatformFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [account: AddressLike, amount: BigNumberish];
      export type OutputTuple = [account: string, amount: bigint];
      export interface OutputObject {account: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkDeliveredEvent {
      export type InputTuple = [escrowId: BigNumberish, seller: AddressLike];
      export type OutputTuple = [escrowId: bigint, seller: string];
      export interface OutputObject {escrowId: bigint, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EscrowEvents extends BaseContract {
    
    connect(runner?: ContractRunner | null): EscrowEvents;
    waitForDeployment(): Promise<this>;

    interface: EscrowEventsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'DisputeRaised'): TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'ETHDeposited'): TypedContractEvent<ETHDepositedEvent.InputTuple, ETHDepositedEvent.OutputTuple, ETHDepositedEvent.OutputObject>;
getEvent(key: 'ETHRescued'): TypedContractEvent<ETHRescuedEvent.InputTuple, ETHRescuedEvent.OutputTuple, ETHRescuedEvent.OutputObject>;
getEvent(key: 'EscrowAccepted'): TypedContractEvent<EscrowAcceptedEvent.InputTuple, EscrowAcceptedEvent.OutputTuple, EscrowAcceptedEvent.OutputObject>;
getEvent(key: 'EscrowCancelled'): TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'EscrowFunded'): TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'PaymentReleased'): TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
getEvent(key: 'PlatformFeeProposed'): TypedContractEvent<PlatformFeeProposedEvent.InputTuple, PlatformFeeProposedEvent.OutputTuple, PlatformFeeProposedEvent.OutputObject>;
getEvent(key: 'PlatformFeeUpdated'): TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
getEvent(key: 'WorkDelivered'): TypedContractEvent<WorkDeliveredEvent.InputTuple, WorkDeliveredEvent.OutputTuple, WorkDeliveredEvent.OutputObject>;

    filters: {
      
      'DisputeRaised(uint256,address)': TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
      DisputeRaised: TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
    

      'DisputeResolved(uint256,address,uint256)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'ETHDeposited(address,uint256)': TypedContractEvent<ETHDepositedEvent.InputTuple, ETHDepositedEvent.OutputTuple, ETHDepositedEvent.OutputObject>;
      ETHDeposited: TypedContractEvent<ETHDepositedEvent.InputTuple, ETHDepositedEvent.OutputTuple, ETHDepositedEvent.OutputObject>;
    

      'ETHRescued(address,uint256)': TypedContractEvent<ETHRescuedEvent.InputTuple, ETHRescuedEvent.OutputTuple, ETHRescuedEvent.OutputObject>;
      ETHRescued: TypedContractEvent<ETHRescuedEvent.InputTuple, ETHRescuedEvent.OutputTuple, ETHRescuedEvent.OutputObject>;
    

      'EscrowAccepted(uint256,address)': TypedContractEvent<EscrowAcceptedEvent.InputTuple, EscrowAcceptedEvent.OutputTuple, EscrowAcceptedEvent.OutputObject>;
      EscrowAccepted: TypedContractEvent<EscrowAcceptedEvent.InputTuple, EscrowAcceptedEvent.OutputTuple, EscrowAcceptedEvent.OutputObject>;
    

      'EscrowCancelled(uint256,address)': TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
      EscrowCancelled: TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
    

      'EscrowCreated(uint256,address,address,address,uint256,uint256)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'EscrowFunded(uint256,address,uint256)': TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
      EscrowFunded: TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
    

      'FeesWithdrawn(address,uint256)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'PaymentReleased(uint256,address,uint256,uint256)': TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
      PaymentReleased: TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
    

      'PlatformFeeProposed(uint96,uint256)': TypedContractEvent<PlatformFeeProposedEvent.InputTuple, PlatformFeeProposedEvent.OutputTuple, PlatformFeeProposedEvent.OutputObject>;
      PlatformFeeProposed: TypedContractEvent<PlatformFeeProposedEvent.InputTuple, PlatformFeeProposedEvent.OutputTuple, PlatformFeeProposedEvent.OutputObject>;
    

      'PlatformFeeUpdated(uint96,uint96)': TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
      PlatformFeeUpdated: TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    

      'WorkDelivered(uint256,address)': TypedContractEvent<WorkDeliveredEvent.InputTuple, WorkDeliveredEvent.OutputTuple, WorkDeliveredEvent.OutputObject>;
      WorkDelivered: TypedContractEvent<WorkDeliveredEvent.InputTuple, WorkDeliveredEvent.OutputTuple, WorkDeliveredEvent.OutputObject>;
    
    };
  }